<HighscoreScreen>:
    GridLayout:
        cols:1
        rows:11
        Label:
            id: lb0
        Label:
            id: lb1
        Label:
            id: lb2
        Label:
            id: lb3
        Label:
            id: lb4
        Label:
            id: lb5
        Label:
            id: lb6
        Label:
            id: lb7
        Label:
            id: lb8
        Label:
            id: lb9
        Button:
            text: '->'
