# class PinballStatemachine(StateMachine):
#     startup = State('Menu', initial=True)
#     step1 = State('Sammle Malz')
#     step2 = State('Animation Mahlen')
#     step3 = State('Mische das Malz')
#     step4 = State('Animation Läutern')
#     step5 = State('Aktivierung Hopfen')
#     step6 = State('Sammle Hopfen')
#     step7 = State('Hopfen einfüllen')
#     step8 = State('Animation boiling')
#     step9 = State('Hefe züchten')
#     step10 = State('Hefe beifügen')
#     step11 = State('Animation fermentieren')