
GridLayout:
    cols: 2
    rows: 5

    Button:
        text:"Bumper1"
        on_press: app.send("b1")
    Button:
        text:"Target1"
        on_press: app.send("t1")
    Button:
        text:"Bumper2"
        on_press: app.send("b2")
    Button:
        text:"Target2"
        on_press: app.send("t2")
    Button:
        text:"Bumper3"
        on_press: app.send("b3")
    Button:
        text:"Target3"
        on_press: app.send("t3")
    Button:
        text:"Kicker (L)"
        on_press: app.send("kl")
    Button:
        text:"Kicker (R)"
        on_press: app.send("kr")
    Button:
        text:"Exit"
        on_press: app.close()
    Button:
        text:"Ballshooter"
        on_press: app.send("bs")
    
    

